stages:
  - deploy

Mirror on Github:
  stage: deploy
  script:
    - set -e
    - echo 'test'
    - git checkout master
    - git pull
    - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/$GITHUB_REPO